export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOGOUT = 'LOGOUT';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const SET_LOADING = 'SET_LOADING';

export const GET_RECORDS_SUCCESS = 'GET_RECORDS_SUCCESS';
export const GET_RECORDS_FAILURE = 'GET_RECORDS_FAILURE';

export const CALCULATE_BMR_REQUEST = 'CALCULATE_BMR_REQUEST';
export const CALCULATE_BMR_SUCCESS = 'CALCULATE_BMR_SUCCESS';
export const CALCULATE_BMR_FAILURE = 'CALCULATE_BMR_FAILURE';

export const FETCH_FOODS_REQUEST = 'FETCH_FOODS_REQUEST';
export const FETCH_FOODS_SUCCESS = 'FETCH_FOODS_SUCCESS';
export const FETCH_FOODS_FAILURE = 'FETCH_FOODS_FAILURE';

export const ADD_MEAL_SUCCESS = 'ADD_MEAL_SUCCESS';
export const ADD_MEAL_FAILURE = 'ADD_MEAL_FAILURE';

export const ADD_YOUR_FOOD_SUCCESS = 'ADD_YOUR_FOOD_SUCCESS';
export const ADD_YOUR_FOOD_FAILURE = 'ADD_YOUR_FOOD_FAILURE'; 

export const GET_MEALS_SUCCESS = 'GET_MEALS_SUCCESS';
export const GET_MEALS_FAILURE = 'GET_MEALS_FAILURE';

export const GET_FOODS_SUCCESS = 'GET_FOODS_SUCCESS';
export const GET_FOODS_FAILURE = 'GET_FOODS_FAILURE'; 

export const ADD_FOOD_SUCCESS = 'ADD_FOOD_SUCCESS';
export const ADD_FOOD_FAILURE = 'ADD_FOOD_FAILURE'; 


export const EDIT_FOOD_SUCCESS = 'EDIT_FOOD_SUCCESS'; 
export const EDIT_FOOD_FAILURE = 'EDIT_FOOD_FAILURE'; 

export const DELETE_FOOD_SUCCESS = 'DELETE_FOOD_SUCCESS';
export const DELETE_FOOD_FAILURE = 'DELETE_FOOD_FAILURE'; 

export const DELETE_MEAL_FOOD_SUCCESS = 'DELETE_MEAL_FOOD_SUCCESS';
export const DELETE_MEAL_FOOD_FAILURE = 'DELETE_MEAL_FOOD_FAILURE'; 
