export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOGOUT = 'LOGOUT';


export const SEND_MESSAGE = 'SEND_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const SET_LOADING = 'SET_LOADING';

export const GET_RECORDS_SUCCESS = 'GET_RECORDS_SUCCESS';
export const GET_RECORDS_FAILURE = 'GET_RECORDS_FAILURE';

export const CALCULATE_BMR_REQUEST = 'CALCULATE_BMR_REQUEST';
export const CALCULATE_BMR_SUCCESS = 'CALCULATE_BMR_SUCCESS';
export const CALCULATE_BMR_FAILURE = 'CALCULATE_BMR_FAILURE';
